### ISSUE TITLE
How to posts

### ISSUE THREAD

**Issue by geotheory** [ohduran/Onassis#3]
Thanks for this lovely theme.

In the `tutorials/2019-10-18-welcome-to-jekyll.html` post it says _"You’ll find this post in your _posts directory. Go ahead and edit it and re-build the site to see your changes"_.  But in fact this is being built from `collections/_tutorials/2019-10-18-welcome-to-jekyll.markdown`.  When I rename the other file to `_posts/2019-10-13-welcome-to-jekyll2.markdown` it has no effect on what is rendered.  Is this intended behaviour?

Because of this I'm unclear how to implement the normal compiling of `_posts/*.md` posts, and mapping to `/posts/` subfolder in the URL.  Any suggestion appreciated.

**Comment by ohduran** [comment]
Hi @geotheory, thank you so much for your kind words. The welcome-to-jekyll post is the default one, and this is an error on my part since the structure of the code is different than the default one. Sorry about the confusion.

I can confirm to you that each collection, be it articles, letters, speeches or tutorials, is where posts must be contained, and you must disregard the `_posts` folder. I encourage you to open a PR on this if you can find the time to do so, as contributions are always appreciated.

In case that you want to create a new collection, you can do so as explained in [the documentation](https://jekyllrb.com/docs/collections/): first, by modifying the collection section on the `config.yml` file. And second, by adding the corresponding folder `_foldername` on the `collections` folder.

Hope this comment finds you well. Alvaro.

**Comment by geotheory** [comment]
Thanks for clarrifying, Alvaro. That's no problem, I've used the articles folder instead. Just useful to know what is supported.
